### ISSUE TITLE
Indicator: cumulative number of alien species

### ISSUE THREAD

**Issue by timadriaens** [trias-project/indicators#20] opened 2018-03-27 15:17 UTC
## Description
This indicator measures the trends of all alien species introductions (publication of first observations). At the national level this indicator is useful to measure the trends in the presence/occurrence of alien (and potentially invasive) species and inform decisions to do with prevention of alien species introduction and the management and control of invasive species causing impacts on biodiversity and ecosystems. It is based on the same information for #17 but is an alternative representation in line with international policy indicators on (invasive) alien species such as EU headline indicators, SEBI, Aichi, IPBES.

Data needs and data output are the same as #17. 

## Visualisation
A lineplot is envisaged with colours for breakdowns. Visualizing uncertainty due to use of time periods is discussed in #18

**Comment by stijnvanhoey** [comment] 2018-04-16 09:38
As a reference, the figure looks from the previous indicator report:
![image](https://user-images.githubusercontent.com/754862/38801625-a26968aa-416a-11e8-948c-b7fa15176f3c.png)

**Comment by SanderDevisscher** [comment] 2018-04-16 10:17
Due to lack of habitat information I opted to just create the cumulative sum of alien species. The script is based on earlier work from Stijn (see https://github.com/inbo/natuurindicatoren/blob/master/src/bedreiging-door-nieuwe-uitheemse-diersoorten.Rmd) and Damiano and calculates how many species are present in a given year. Presence for a given year is determined by checking, per species, if the year falls between the startDate (first observation) and endDate (last observation) for that species. 

@timadriaens, @qgroom @SoVDH should determine whether to use a line or bar graph 

![English line graph](https://user-images.githubusercontent.com/16779320/38803609-0bf54960-4170-11e8-82c2-95753b73633e.png)

![English bar graph](https://user-images.githubusercontent.com/16779320/38803480-aaeaba42-416f-11e8-9fef-f246004fe941.png)

suggestion: When using a bar graph a grouping should occur (for example by decade)

**Comment by qgroom** [comment] 2018-04-16 12:58
We only need to start the graph much later.
For policy purposes we could start somewhere between 1900 and 1950.
It might be interesting to have the curve split into plants, vertebrates, invertebrates and fungi and others.

**Comment by stijnvanhoey** [comment] 2018-04-16 13:01
As this is relevant for the other indicators as well, @SanderDevisscher and @Yasmine-Verzelen make sure this is a seperately defined variable, e.g. :

```
start_year_plot <- 1945
```

**Comment by stijnvanhoey** [comment] 2018-04-16 13:08
@SanderDevisscher and @Yasmine-Verzelen , I also would agree on the year x-scale steps:
e.g. 
```
x_scale_stepsize <- 10
scale_x_continuous(breaks = seq(start_year_plot, max(data$startDate), x_scale_stepsize)))
```
We can include this idea in each indicator graph. @Yasmine-Verzelen make `x_scale_stepsize` an input argument of your function as well (with default 10).

**Comment by qgroom** [comment] 2018-04-16 13:12
10 years would make it a very insenitive indicator. In policy terms 10 years is a long time.
I would not go longer than 5 years unless it is absolutely necessary.

**Comment by stijnvanhoey** [comment] 2018-04-16 13:14
We are talking about labels only, not aggregations, so that will be ok ;-)

**Comment by stijnvanhoey** [comment] 2018-04-16 13:29
compare from 1800:
![image](https://user-images.githubusercontent.com/754862/38811735-9ed2dc74-418a-11e8-86aa-92d451f0dad2.png)

versus from 1900:
![image](https://user-images.githubusercontent.com/754862/38811789-d71c3c2e-418a-11e8-9dbb-00dc2981e6ed.png)

versus from 1950:
![image](https://user-images.githubusercontent.com/754862/38811758-bc3ae586-418a-11e8-8ba5-3d0372e2de49.png)

@qgroom, fits this with your idea of having it more policy-oriented?

**Comment by stijnvanhoey** [comment] 2018-04-16 13:56
@timadriaens can you have a check as well?

**Comment by qgroom** [comment] 2018-04-16 14:02
Indeed! @LienReyserhove @timadriaens and I need to work more getting species into the unified checklist. Some of the steep rise is the result of increased prospecting for plants. This will not bo so distinct as we add more taxa.

**Comment by stijnvanhoey** [comment] 2018-04-17 06:48
Yesterday, we were a bit stuck with the implementation to easily  add the facet-options to the graph. I revisited the implementation and I think we can easily solve this issue by altering the data set, adding individial rows for each year in between the start/end range. By doing so, we can easily count rows (`groupby %>% count()`), both for all records as well as taking into account the facet/groupby of a category. 

The concept is as follows:
```
test <- data.frame(start = c(1204, 1202, 1201, 1201), 
                   end = c(1208, 1208, 1208, 1208),
                   key = 1:4)
test <- test %>% 
    rowwise() %>%
    do(years = .data$start:.data$end) %>%
    bind_cols(test) %>% 
    unnest(years)
```
with the output:

```
# A tibble: 28 x 4
   start   end   key years
   <dbl> <dbl> <int> <int>
 1  1204  1208     1  1204
 2  1204  1208     1  1205
 3  1204  1208     1  1206
 4  1204  1208     1  1207
 5  1204  1208     1  1208
 6  1202  1208     2  1202
 7  1202  1208     2  1203
 8  1202  1208     2  1204
 9  1202  1208     2  1205
10  1202  1208     2  1206
# ... with 18 more rows
```
As such, the problem is a regular counting problem, grouped by year

**Comment by SanderDevisscher** [comment] 2018-04-17 06:55
@stijnvanhoey I'll try to implement this

**Comment by stijnvanhoey** [comment] 2018-04-17 06:59
@SanderDevisscher I have some commits almost ready to push, so take a coffee first ;-)

something to think about: How to treat `NA` for respectively:

- `startDate` -> not taking into account?
- `endDate` -> just take `now()`?

**Comment by SanderDevisscher** [comment] 2018-04-17 07:54
@LienReyserhove when creating the checklist how did you treat established species with NA's in endDate ?

**Comment by SanderDevisscher** [comment] 2018-04-17 09:57
@stijnvanhoey since your update I get this error: 
![image](https://user-images.githubusercontent.com/16779320/38862926-8ba71e42-4236-11e8-90a8-0f395f1b370e.png)

**Comment by SanderDevisscher** [comment] 2018-04-17 11:04
I was able to produce this:
**Kingdom**
![image](https://user-images.githubusercontent.com/16779320/38865791-2c438fcc-423f-11e8-9089-c48b9b371bfa.png)

**Phylum**
![image](https://user-images.githubusercontent.com/16779320/38865771-196209ba-423f-11e8-87b2-ad195c484c34.png)

**Pathway level1**
![image](https://user-images.githubusercontent.com/16779320/38865972-c1cc824c-423f-11e8-9d74-8ad6a716be7c.png)

however this is the result for family and other diverse facet columns:
![image](https://user-images.githubusercontent.com/16779320/38865844-58f24d74-423f-11e8-8b5d-f894a59e8211.png)

**Comment by LienReyserhove** [comment] 2018-04-17 12:14
@stijnvanhoey and @SanderDevisscher with respect to the NA's in the data:

if `NA` is in the end date, we used to consider them to be present until the date of the last publication of the checklist, which in the case of MAP is 2018. 

However, recently, we agreed to change this approach and to considered these species to be present only in that specific year. E.g. if a species was recorded first in 1982 and has no end date, then eventDate is 1982/1982. Same thing when there's no start_year.
We discussed this issue for the Rust fungi checklist, and I suggest to keep this approach for the MAP. 
@qgroom you agree?

**Comment by LienReyserhove** [comment] 2018-04-17 12:16
See also https://github.com/trias-project/uredinales-belgium-checklist/pull/6#issuecomment-379056292

**Comment by peterdesmet** [comment] 2018-04-17 12:33
@stijnvanhoey what you suggest in https://github.com/trias-project/pipeline/issues/20#issuecomment-381867702 would also allow to make the chart with line (`start`) and error line (`year`) I suggest in https://github.com/trias-project/pipeline/issues/18#issuecomment-380814490.

**Comment by stijnvanhoey** [comment] 2018-04-17 12:36
With regard to the NA for endDate; currently indeed not an issue:
```
> nrow(data %>% filter(is.na(endDate), !is.na(startDate)))
[1] 0
```
versus: 
```
> nrow(data %>% filter(!is.na(endDate), !is.na(startDate)))
[1] 13438
```
but to make sure, what do we do in the visualisation after the check for endDate NA when startDate not NA:

- provide an error, as we expect this to be part of the checklist creation process?
- provide a warning, but adapt it?
- provide no warning, just accept endDate == startDate in this situation?

**Comment by stijnvanhoey** [comment] 2018-04-17 12:38
@peterdesmet I'm not completely sure how your suggestion will exactly turn out, but that is indeed the case. Implementation is [now refactored](https://github.com/trias-project/pipeline/pull/25/commits/0ab31b1dcaf28787375bea529475e9725241482f) and @SanderDevisscher made sure it works with the subplots as well in the meanwhile. So, your uncertainty suggestion seems like an appropriate next step.

**Comment by SanderDevisscher** [comment] 2018-04-17 13:28
@stijnvanhoey how important is the only_colnames = TRUE argument in assert_colnames ? cause it throws this error _"Error in assert_colnames(df, colnames = c("key", "startDate", "endDate"), : These columns exist in your dataframe but not in colnames: nubKey scientificName datasetKey species genus family order class phylum kingdom rank taxonomicStatus acceptedKey accepted locationId locality country status establishmentMeans source.x type description source.y pathway_level1 pathway_level2"_

setting the value to FALSE fixes the problem

**Comment by stijnvanhoey** [comment] 2018-04-17 14:05
@SanderDevisscher fixed that issue, see latest commit on the branch

**Comment by damianooldoni** [comment] 2019-07-04 10:02
This issue can be closed as indicator is working well.

**Closed by damianooldoni** 2019-07-04 10:02 UTC
